DECLARE @Unvan AS INT = 0, @Departman INT--AS VARCHAR(50)
/*	SELECT @Unvan= 
	CASE WHEN COUNT('$PActiveUser$' )>0 then 1 else 0 END,
	@Departman =Departman,
	
	FROM OCT88_DEPARTMANLAR D WITH (NOLOCK) WHERE Mudur='$PActiveUser$' 
	GROUP BY Departman
*/

SELECT @Unvan = CASE 
	WHEN (SELECT COUNT(*) FROM OCT88_DEPARTMANLAR D WITH (NOLOCK) WHERE Mudur='$PActiveUser$') > 0 THEN 4
	WHEN(SELECT COUNT(*) FROM OCT88_PROJE_TANITIMLARI P WITH (NOLOCK) WHERE P.ProjeSorumlusu='$PActiveUser$') > 0 THEN 5
	ELSE ' ' END
	
SELECT @Departman = CASE 
	WHEN 
		(SELECT COUNT(Departman)
			FROM OCT88_DEPARTMANLAR D WITH (NOLOCK) 
			WHERE Mudur='$PActiveUser$') > 0 
	THEN 
		(SELECT TOP 1 UserTableID
			FROM OCT88_DEPARTMANLAR D WITH (NOLOCK) 
			WHERE Mudur='$PActiveUser$')
	WHEN 
		(SELECT COUNT(PG.Departman) 
			FROM OCT88_PROJE_TANITIMLARI P WITH (NOLOCK) 
			LEFT JOIN OCT88_PROJE_GOREV_ADIMLARI AS PG WITH(NOLOCK) 
				ON PG.HizmetTuru = P.HizmetTuru
			WHERE P.ProjeSorumlusu='$PActiveUser$') > 0
	THEN 
		(SELECT TOP 1 PG.Departman 
		FROM OCT88_PROJE_TANITIMLARI P WITH (NOLOCK) 
		LEFT JOIN OCT88_PROJE_GOREV_ADIMLARI AS PG WITH(NOLOCK) 
			ON PG.HizmetTuru = P.HizmetTuru
		WHERE P.ProjeSorumlusu='$PActiveUser$')
	ELSE 0 END
	
	
	
IF @Unvan=4

BEGIN

	SELECT 
		G.UserTableID,
		G.FormTypeID,
		D.Departman,
		PT.ProjeAdi AS [Proje Adı],
		F.Unvan,
		PGAD.GorevAdimi AS [Görev Adımı],
		XCU.UserFullName AS Sorumlu,
		G.Durum
		
	FROM OCT88_GOREVLER G WITH (NOLOCK)
	
	LEFT OUTER JOIN OCT88_GOREVLERIM_FORMU_DETAY GFD WITH (NOLOCK) 
		ON G.GID=GFD.UserTableID
	LEFT OUTER JOIN OCT88_PROJE_GOREV_ADIMLARI_DETAY PGAD WITH (NOLOCK) 
		ON PGAD.UserTableID=GFD.GAID
	LEFT OUTER JOIN OCT88_PROJE_TANITIMLARI PT WITH (NOLOCK) 
		ON PGAD.MasterID=PT.UserTableID
	LEFT OUTER JOIN XPODA_CLIENT_USERS XCU WITH (NOLOCK) 
		ON GFD.Sorumlu=XCU.UserID
	LEFT OUTER JOIN OCT88_FIRMALAR F WITH (NOLOCK) 
		ON F.UserTableID= PT.Musteri	
	LEFT OUTER JOIN OCT88_DEPARTMANLAR D WITH (NOLOCK) 
		ON D.UserTableID=PGAD.Departman
	WHERE G.Durum='Tamamlandı' AND D.UserTableID=@Departman AND G.OnayliGorev=0 AND GFD.GorevSon=1	
	
	
END	
ELSE IF @Unvan=5
BEGIN
	SELECT DISTINCT

			PT.UserTableID,
			PT.FormTypeID,
			PT.ProjeAdi AS [Proje Adı],
			H.HizmetTuru AS [Hizmet Türü],
			D.Departman,
			F.Unvan,
			PT.ProjeDurumu AS [Proje Durumu]

	FROM OCT88_PROJE_TANITIMLARI PT WITH (NOLOCK) 

	LEFT OUTER JOIN OCT88_PROJE_GOREV_ADIMLARI_DETAY PGAD WITH (NOLOCK) 
		ON PGAD.MasterID=PT.UserTableID 
	LEFT OUTER JOIN OCT88_GOREVLERIM_FORMU_DETAY GFD WITH (NOLOCK) 
		ON PGAD.UserTableID=GFD.GAID AND GFD.GorevSon=1	
	LEFT OUTER JOIN OCT88_GOREVLER G WITH (NOLOCK)
		ON GFD.UserTableID=G.GID and G.Durum='Onaylandı' 
	LEFT OUTER JOIN OCT88_DEPARTMANLAR D WITH (NOLOCK) 
		ON D.UserTableID=PGAD.Departman
	LEFT OUTER JOIN OCT88_FIRMALAR F WITH (NOLOCK) 
		ON F.UserTableID= PT.Musteri
	LEFT OUTER JOIN OCT88_HIZMET_TURLERI H WITH (NOLOCK) 
		ON H.UserTableID=PT.HizmetTuru

	WHERE PT.ProjeOnay=0 
	GROUP BY PT.ProjeDurumu,PT.UserTableID,PT.FormTypeID,PT.ProjeAdi ,H.HizmetTuru ,D.Departman,F.Unvan
	HAVING COUNT(G.UserTableID)=COUNT( GFD.UserTableID) AND COUNT(G.UserTableID)>0 AND COUNT( GFD.UserTableID)>0
	

END

ELSE 
BEGIN
SELECT ' '
END